BankingAppTest/Models/BankAccount.cs
using System.ComponentModel.DataAnnotations;

namespace BankingAppTest.Models;

public class BankAccount
{
    [Key] public int Id { get; set; }

    [Required] public string Name { get; set; }

    public double Balance { get; set; }
}

BankingAppTest/Models/ErrorViewModel.cs
namespace BankingAppTest.Models;

public class ErrorViewModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

BankingAppTest/Models/Transaction.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BankingAppTest.Models;

public class Transaction
{
    [Key] public int Id { get; set; }

    [DisplayName("From Account")] public string FromAccount { get; set; }

    [DisplayName("To Account")] public string ToAccount { get; set; }

    [DisplayName("Transaction Time")] public DateTime TransactionTime { get; set; }

    [DisplayName("Amount Debited")] public double AmountDebited { get; set; }

    [DisplayName("From Account Balance")] public double FromAccountBalance { get; set; }

    [DisplayName("To Account Balance")] public double ToAccountBalance { get; set; }
}

BankingAppTest/Models/Transfer.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BankingAppTest.Models;

public class Transfer
{
    [Key] public int Id { get; set; }

    [DisplayName("Expense")] [Required] public string ExpenseName { get; set; }

    [Required]
    [Range(1, int.MaxValue, ErrorMessage = "Amount must be greater than 0!")]
    public double Amount { get; set; }

   // [DisplayName("Expense Type")] public int ExpenseTypeId { get; set; }

    //[ForeignKey("ExpenseTypeId")]
    //public int ExpenseTypeId2 { get; set; }
    //[ForeignKey("ExpenseTypeId2")]
    public virtual BankAccount ExpenseType { get; set; }
}

BankingAppTest/Models/ViewModels/ExpenseVM.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BankingAppTest.Models.ViewModels;

public class ExpenseVM
{
    public Transfer Transfer { get; set; }
    //public BankAccount LocalExpenseType { get; set; }

    [Required] public int FromAccount { get; set; }

    [Required] public int ToAccount { get; set; }

    public IEnumerable<SelectListItem> TypeDropDown { get; set; }
}

BankingAppTest/Controllers/BankAccountController.cs
using BankingAppTest.Data;
using BankingAppTest.Models;
using Microsoft.AspNetCore.Mvc;

namespace BankingAppTest.Controllers;

public class BankAccountController : Controller
{
    private readonly ApplicationDbContext _db;

    public BankAccountController(ApplicationDbContext db)
    {
        _db = db;
    }


    public IActionResult Index()
    {
        IEnumerable<BankAccount> objList = _db.BankAccounts;
        return View(objList);
    }

    // GET-Create
    public IActionResult Create()
    {
        return View();
    }

    // POST-Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(BankAccount obj)
    {
        if (ModelState.IsValid)
        {
            _db.BankAccounts.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        return View(obj);
    }


    // GET Delete
    public IActionResult Delete(int? id)
    {
        if (id == null || id == 0) return NotFound();
        var obj = _db.BankAccounts.Find(id);
        if (obj == null) return NotFound();
        return View(obj);
    }

    // POST Delete
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePost(int? id)
    {
        var obj = _db.BankAccounts.Find(id);
        if (obj == null) return NotFound();

        _db.BankAccounts.Remove(obj);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    // GET Update
    public IActionResult Update(int? id)
    {
        if (id == null || id == 0) return NotFound();
        var obj = _db.BankAccounts.Find(id);
        if (obj == null) return NotFound();
        return View(obj);
    }

    // POST UPDATE
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Update(BankAccount obj)
    {
        if (ModelState.IsValid)
        {
            _db.BankAccounts.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        return View(obj);
    }
}

BankingAppTest/Controllers/HomeController.cs
using System.Diagnostics;
using BankingAppTest.Models;
using Microsoft.AspNetCore.Mvc;

namespace BankingAppTest.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

BankingAppTest/Controllers/TransferController.cs
using BankingAppTest.Data;
using BankingAppTest.Models;
using BankingAppTest.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BankingAppTest.Controllers;

public class TransferController : Controller
{
    private readonly ApplicationDbContext _db;

    public TransferController(ApplicationDbContext db)
    {
        _db = db;
    }
    public IActionResult Index()
    {
        IEnumerable<Transaction> objList = _db.Transactions;
        return View(objList);
    }

    // GET-Create
    public IActionResult Create()
    {
        var expenseVM = new ExpenseVM
        {
            Transfer = new Transfer(),
            TypeDropDown = _db.BankAccounts.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            })
        };

        return View(expenseVM);
    }

    // POST-Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(ExpenseVM obj)
    {
        
        if ( obj.FromAccount.Equals(0) || obj.ToAccount.Equals(0))
        {
            return View(obj);
        }
        if (!ModelState.IsValid)
        {
            var fromAccount = _db.BankAccounts.FirstOrDefault(u => u.Id == obj.FromAccount);
            var toAccount = _db.BankAccounts.FirstOrDefault(u => u.Id == obj.ToAccount);
            
            //Create new fund transaction
            var newTransaction = new Transaction
            {
                FromAccount = fromAccount.Name,
                ToAccount = toAccount.Name,
                TransactionTime = DateTime.Now,
                AmountDebited = obj.Transfer.Amount,
                FromAccountBalance = fromAccount.Balance,
                ToAccountBalance = toAccount.Balance
            };
            //if not enough balance on from account, or trying to transfer to oneself
            if (fromAccount.Balance < obj.Transfer.Amount || obj.FromAccount.Equals(obj.ToAccount))
            {
                return View(obj);
            }
            //update balances
            fromAccount.Balance = fromAccount.Balance - obj.Transfer.Amount;
            toAccount.Balance = toAccount.Balance + obj.Transfer.Amount;

            //write new balances to database
            _db.BankAccounts.Update(fromAccount);
            _db.BankAccounts.Update(toAccount);

            //add new transaction
            _db.Transactions.Add(newTransaction);
            
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        return View(obj);
    }

    // GET Update
    public IActionResult Update(int? id)
    {
        var expenseVM = new ExpenseVM
        {
            Transfer = new Transfer(),
            TypeDropDown = _db.BankAccounts.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            })
        };
        var viewTransaction = new Transaction();
        if (id == null || id == 0) return NotFound();
        viewTransaction = _db.Transactions.Find(id);
      
        return View(viewTransaction);
    }
}

BankingAppTest/Views/BankAccount/Create.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model BankAccount

<form method="post" asp-action="Create">
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Create Account</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="Name"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="Name" class="form-control"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="Balance"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="Balance" class="form-control"/>
                        <span asp-validation-for="Balance" class="text-danger"></span>
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="create"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

BankingAppTest/Views/BankAccount/Delete.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model BankAccount

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden/>
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Delete Account</h2>

            <h3 class="text-black-50 pl-3"> <br/>Are you sure you want to delete this account?</h3>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="Name"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="Name" disabled class="form-control"/>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="Balance"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="Balance" disabled class="form-control"/>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-75" value="Delete"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-75">Back to List</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

BankingAppTest/Views/BankAccount/Index.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<BankAccount>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">All Accounts</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="BankAccount" asp-action="Create" class="btn btn-primary">Create new Account</a>
        </div>
    </div>
    <br/>

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
            <tr>
                <th>
                    Account Name
                </th>
                <th>
                    Balance
                </th>
                <th>
                    Changes
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="35%">@obj.Name</td>
                    <td width="35%">@obj.Balance</td>
                    <td width="30%">
                        <div class="w-100 btn-group"role="group">
                            <a asp-controller="BankAccount" asp-action="Update" asp-route-Id="@obj.Id" class="btn btn-primary mx-1">Edit</a>
                            <a asp-controller="BankAccount" asp-action="Delete" asp-route-Id="@obj.Id" class="btn btn-danger mx-1">Delete</a>
                        </div>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    }
    else
    {
        <p>No Accounts created yet</p>
    }

</div>

BankingAppTest/Views/BankAccount/Update.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model BankAccount

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden/>
    <div class="border p-3">

        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Edit Account</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="Name"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="Name" class="form-control"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="Balance"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="Balance" class="form-control"/>
                        <span asp-validation-for="Balance" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Save"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back to List</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

BankingAppTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to banking app</h1>

    <p>View all Accounts <a asp-area="" asp-controller="BankAccount" asp-action="Index">here</a>.</p>
    <p>Initiate a transfer <a asp-area="" asp-controller="Transfer" asp-action="Create">here</a>.</p>
    <p>View all Transactions <a asp-area="" asp-controller="Transfer" asp-action="Index">here</a>.</p>
</div>

BankingAppTest/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Banking App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="180x180" href="assets/img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="assets/img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="assets/img/favicon-16x16.png">
    <link rel="manifest" href="assets/img/site.webmanifest">
    <link rel="mask-icon" href="assets/img/safari-pinned-tab.svg" color="#5bbad5">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Banking App</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="BankAccount" asp-action="Index">All Accounts</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Transfer" asp-action="Index">All Transactions</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Transfer" asp-action="Create">Transfer Funds</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - Banking App - <a href="https://www.alonsomiguel.com/" target="_blank">Miguel Alonso</a> |
        <a href="https://github.com/MiguelAlonso1" target="_blank" class="github">
            <i class="bx bxl-github"></i>
        </a> |
        <!--  <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a> -->
        <a href="https://www.linkedin.com/in/migalonso/" target="_blank" class="linkedin">
            <i class="bx bxl-linkedin"></i>
        </a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://kit.fontawesome.com/7da995a2ae.js" crossorigin="anonymous"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>

BankingAppTest/Views/Transfer/Create.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model BankingAppTest.Models.ViewModels.ExpenseVM

<form method="post" asp-action="Create">
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Transfer Funds</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Transfer.ExpenseType">From Account</label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Transfer.ExpenseName">To Account</label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Transfer.Amount">Amount to Transfer</label>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <select asp-for="@Model.FromAccount" asp-items="@Model.TypeDropDown" class="form-control">
                            <option selected>--From Account--</option>
                        </select>
                        <span asp-validation-for="@Model.FromAccount" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <select asp-for="@Model.ToAccount" asp-items="@Model.TypeDropDown" class="form-control">
                            <option selected>--To Account--</option>
                        </select>
                        <span asp-validation-for="@Model.ToAccount" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input asp-for="Transfer.Amount" class="form-control"/>
                        <span asp-validation-for="Transfer.Amount" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Transfer"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back to Transactions</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

BankingAppTest/Views/Transfer/Index.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<Transaction>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">All Transactions</h2>
        </div>
         <div class="col-6 text-right">
            <a asp-controller="Transfer" asp-action="Create" class="btn btn-primary">Initiate New Transfer</a>
        </div>
    </div>
    <br/>

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
            <tr>
                <th>
                    From Account
                </th>
                <th>
                    To Account
                </th>
                <th>
                    Transaction Time
                </th>

                <th>
                    Amount Debited
                </th>
                <th>
                    From Account Balance
                </th>

                <th>
                    To Account Balance
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="20%">@obj.FromAccount</td>
                    <td width="20%">@obj.ToAccount</td>
                    <td width="20%">@obj.TransactionTime</td>
                    <td width="20%">@obj.AmountDebited</td>
                    <td width="30%">@obj.FromAccountBalance</td>
                    <td width="30%">@obj.ToAccountBalance</td>

                    <td width="25%">
                        <div class="w-100 btn-group"role="group">
                            <a asp-controller="Transfer" asp-action="Update" asp-route-Id="@obj.Id" class="btn btn-primary mx-1">Details</a>
                            @*                            <a asp-controller="ExpenseType" asp-action="Delete" asp-route-Id="@obj.Id" class="btn btn-danger mx-1">Delete</a>
*@
                        </div>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    }
    else
    {
        <p>No Funds Transfers Processed Yet</p>
    }

</div>

BankingAppTest/Views/Transfer/Update.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Transaction

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden/>
    <div class="border p-3">

        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Transaction Details</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="FromAccount"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="FromAccount" class="form-control" readonly="readonly"/>
                        <span asp-validation-for="FromAccount" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="ToAccount"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="ToAccount" class="form-control" readonly="readonly"/>
                        <span asp-validation-for="ToAccount" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="TransactionTime"></label>
                    </div>
                </div>


                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="TransactionTime" class="form-control" readonly="readonly"/>
                        <span asp-validation-for="TransactionTime" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="AmountDebited"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="AmountDebited" class="form-control" readonly="readonly"/>
                        <span asp-validation-for="AmountDebited" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="FromAccountBalance"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="FromAccountBalance" class="form-control" readonly="readonly"/>
                        <span asp-validation-for="FromAccountBalance" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="ToAccountBalance"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="ToAccountBalance" class="form-control" readonly="readonly"/>
                        <span asp-validation-for="ToAccountBalance" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        @* <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Save" />
                        </div>*@
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back to List</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}